https://morvanzhou.github.io/tutorials/machine-learning/torch/2-02-variable/

# Variable

In [1]:
import torch
from torch.autograd import Variable

tensor = torch.FloatTensor([[1,2],[3,4]])
# requires_grad是参不参与反向传播，要不要计算梯度
variable =Variable(tensor,requires_grad=True)

In [2]:
print(tensor)

tensor([[1., 2.],
        [3., 4.]])


In [3]:
print(variable)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


# Variable 计算，梯度

### tensor计算和variable计算的对比

In [4]:
t_out = torch.mean(tensor*tensor)
v_out = torch.mean(variable*variable)
print(
    '\nt_out:',t_out
)
print(
    '\nv_out:',v_out
)


t_out: tensor(7.5000)

v_out: tensor(7.5000, grad_fn=<MeanBackward1>)


**Variable计算时，它在背景幕布后面一步步默默地搭建着一个庞大的系统, 叫做计算图, computational graph. 这个图是用来干嘛的? 原来是将所有的计算步骤 (节点) 都连接起来, 最后进行误差反向传递的时候, 一次性将所有 variable 里面的修改幅度 (梯度) 都计算出来, 而 tensor 就没有这个能力啦.**

In [5]:
v_out.backward()    # 模拟 v_out 的误差反向传递

# 下面两步看不懂没关系, 只要知道 Variable 是计算图的一部分, 可以用来传递误差就好.
# v_out = 1/4 * sum(variable*variable) 这是计算图中的 v_out 计算步骤
# 针对于 v_out 的梯度就是, d(v_out)/d(variable) = 1/4*2*variable = variable/2

print(variable.grad)    # 初始 Variable 的梯度

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


# 获取 Variable 里面的数据 

### Variable形式

In [6]:
print(variable)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


### tensor形式

In [7]:
print(variable.data)

tensor([[1., 2.],
        [3., 4.]])


### numpy形式

In [8]:
print(variable.data.numpy())

[[1. 2.]
 [3. 4.]]
