In [3]:
import torch as t
from torch.autograd import Variable
#使用Tensor新建一个Variable
x = Variable(t.ones(2,2), requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
y=x.sum()
y

tensor(4., grad_fn=<SumBackward0>)

In [5]:
y.grad_fn

In [6]:
y.backward() #反向传播，计算梯度

In [7]:
# y=x.sum() = (x[0][0] + x[0][1] + x[1][0] + x[1][1])
#每个值的梯度都为1
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [8]:
y.backward()
x.grad

tensor([[2., 2.],
        [2., 2.]])

In [9]:
y.backward()
x.grad

tensor([[3., 3.],
        [3., 3.]])

In [10]:
#一下画线结束的函数是inplace操作
x.grad.data.zero_()

tensor([[0., 0.],
        [0., 0.]])

In [12]:
y.backward()
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [15]:
x=Variable(t.ones(4,5))
y=t.cos(x)
x_tensor_cos=t.cos(x.data)
print(y)
x_tensor_cos

tensor([[0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403]])


tensor([[0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403]])