In [1]:
from __future__ import print_function
import torch as t

# 基础操作

##  创建Tensor

In [2]:
#指定tensor的形状
a=t.Tensor(2,3)
a #数值取决于内存空间的状态

tensor([[0.0000, 0.0000,    nan],
        [0.0000, 0.0000, 0.0000]])

In [3]:
#用list的数据创建tensor
b=t.Tensor([[1,2,3],[4,5,6]])
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
b.tolist() #把tensor转换成list

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [5]:
b_size=b.size()
b_size

torch.Size([2, 3])

In [6]:
b.numel() #b中元素总个数，2*3，等价于b.nelement()

6

In [7]:
b.nelement()

6

In [8]:
#创建一个和b形状一样的tensor
c=t.Tensor(b_size)
#创建一个元素为2和3的tensor
d=t.tensor((2,3))
c,d

(tensor([[0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000]]), tensor([2, 3]))

In [9]:
#tensor.shape等价于tensor.size()
c.shape

torch.Size([2, 3])

In [10]:
c.size()

torch.Size([2, 3])

In [11]:
c.shape??

In [12]:
t.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
t.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
t.arange(1,6,2)

tensor([1, 3, 5])

In [15]:
t.linspace(1,10,3)

tensor([ 1.0000,  5.5000, 10.0000])

In [16]:
t.randn(2,3)

tensor([[-0.9255,  0.2530, -0.1728],
        [ 0.7241, -0.3998,  0.7581]])

In [17]:
t.randperm(5)#长度为5的随机排列

tensor([4, 3, 2, 1, 0])

In [18]:
t.eye(2,3)#对角线为1，不要求行列数一样

tensor([[1., 0., 0.],
        [0., 1., 0.]])

##  常用Tensor操作

view不会修改自身的数据   必须保证调整前后元素总数一致

In [19]:
a=t.arange(0,6)
a

tensor([0, 1, 2, 3, 4, 5])

In [20]:
a.view(2,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [21]:
b=a.view(-1,3) #当某一维为-1的时候，会自动计算它的大小
b

tensor([[0, 1, 2],
        [3, 4, 5]])

In [22]:
b.unsqueeze(1) #注意形状，在第一维（下标从0开始）上增加“1”

tensor([[[0, 1, 2]],

        [[3, 4, 5]]])

In [23]:
b.unsqueeze(-2) #-2表示倒数第二个维度

tensor([[[0, 1, 2]],

        [[3, 4, 5]]])

In [24]:
c=b.view(1,1,1,2,3)
c

tensor([[[[[0, 1, 2],
           [3, 4, 5]]]]])

In [25]:
c.squeeze(0) #压缩第0维的“1”

tensor([[[[0, 1, 2],
          [3, 4, 5]]]])

In [26]:
c.squeeze() #把所有维度为“1”的压缩

tensor([[0, 1, 2],
        [3, 4, 5]])

In [27]:
a[1]=100
b #a和b共享内存，修改了a,b也变了

tensor([[  0, 100,   2],
        [  3,   4,   5]])

resize 调整前后元素总数可以不一样,超过原来尺寸，会自动分配新的内存空间，如果小于原来尺寸，则之前的数据依旧会被保存

In [28]:
b

tensor([[  0, 100,   2],
        [  3,   4,   5]])

In [29]:
b.resize_(1,3)
b

tensor([[  0, 100,   2]])

In [30]:
b.resize_(3,3) #旧的数据依旧保存着，多出的数据会分配新的空间
b

tensor([[            0,           100,             2],
        [            3,             4,             5],
        [            0,             0, 1387558477424]])

## 索引操作 

In [31]:
a=t.randn(3,4)
a

tensor([[-1.7541,  1.2782,  1.3723, -0.4852],
        [ 0.1427,  0.6470, -0.2048, -0.4111],
        [ 1.6884,  0.5317,  1.6554, -0.3520]])

In [32]:
a[0] #第0行（下标从0开始）

tensor([-1.7541,  1.2782,  1.3723, -0.4852])

In [33]:
a[:,0] #第0列

tensor([-1.7541,  0.1427,  1.6884])

In [34]:
a[0][2]

tensor(1.3723)

In [35]:
a[0,-1]

tensor(-0.4852)

In [36]:
a[:2]

tensor([[-1.7541,  1.2782,  1.3723, -0.4852],
        [ 0.1427,  0.6470, -0.2048, -0.4111]])

In [37]:
a[:2,0:2]

tensor([[-1.7541,  1.2782],
        [ 0.1427,  0.6470]])

In [38]:
print(a[0:1,:2])
print(a[0,:2])

tensor([[-1.7541,  1.2782]])
tensor([-1.7541,  1.2782])


In [39]:
a > 1 #返回一个ByteTensor

tensor([[0, 1, 1, 0],
        [0, 0, 0, 0],
        [1, 0, 1, 0]], dtype=torch.uint8)

In [40]:
a[a>1] #等价于a.masked_select(a>1)
#选择结果与原tensor不共享内存空间

tensor([1.2782, 1.3723, 1.6884, 1.6554])

In [41]:
a

tensor([[-1.7541,  1.2782,  1.3723, -0.4852],
        [ 0.1427,  0.6470, -0.2048, -0.4111],
        [ 1.6884,  0.5317,  1.6554, -0.3520]])

In [42]:
a[t.LongTensor([0,1])] #第0行和第1行

tensor([[-1.7541,  1.2782,  1.3723, -0.4852],
        [ 0.1427,  0.6470, -0.2048, -0.4111]])

In [43]:
a=t.arange(0,16).view(4,4)
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [44]:
#选取对角线的元素
index=t.LongTensor([[0,1,2,3]])
a.gather(0,index)

tensor([[ 0,  5, 10, 15]])

In [45]:
#选取反对角线上的元素
index=t.LongTensor([[3,2,1,0]]).t()
a.gather(1,index)

tensor([[ 3],
        [ 6],
        [ 9],
        [12]])

In [46]:
#选取反对角线上的元素，注意与上面的不同
index=t.LongTensor([[3,2,1,0]])
a.gather(0,index)

tensor([[12,  9,  6,  3]])

In [47]:
#选取两个对角线上的元素
index = t.LongTensor([[0,1,2,3],[3,2,1,0]]).t()
b=a.gather(1,index)
b

tensor([[ 0,  3],
        [ 5,  6],
        [10,  9],
        [15, 12]])

In [48]:
#把两个对角线元素放回到指定位置
c = t.zeros(4,4)
c
c.scatter_(1, index, 1.33)

tensor([[1.3300, 0.0000, 0.0000, 1.3300],
        [0.0000, 1.3300, 1.3300, 0.0000],
        [0.0000, 1.3300, 1.3300, 0.0000],
        [1.3300, 0.0000, 0.0000, 1.3300]])

In [49]:
c.scatter_??

In [50]:
print(b.type())

torch.LongTensor


In [51]:
print(index.type())

torch.LongTensor


In [52]:
index=t.FloatTensor()

In [53]:
print(index.type())

torch.FloatTensor


# 高级索引

In [54]:
x=t.arange(0,27).view(3,3,3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [55]:
x[[1,2],[1,2],[2,0]] # x[1,1,2]和 x[2,2,0]

tensor([14, 24])

In [56]:
x[[2,1,0],[0],[1]] # x[2,0,1], x[1,0,1] , x[0,0,1]

tensor([19, 10,  1])

In [57]:
x[[0,2],...]  #x[0] 和 x[2]

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

# Tensor类型 

In [86]:
#设置默认tensor,注意参数事字符串
t.set_default_tensor_type('torch.DoubleTensor')

In [87]:
a=t.Tensor(2,3)
a #现在a是DoubleTensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [88]:
#把a转换成IntTensor,等价于b=a.type(t.IntTensor)
b=a.int()
b

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [89]:
c=a.type_as(b)
c

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [90]:
d=a.new(2,3) 
d

tensor([[6.5612e-321, 6.5612e-321, 4.2490e-321],
        [4.2490e-321, 4.4268e-321, 4.4268e-321]])

In [91]:
t.set_default_tensor_type('torch.FloatTensor')

# 逐元素操作

In [84]:
a=t.arange(0,6).view(2,3)
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [85]:
a.type()

'torch.LongTensor'

In [77]:
a=t.FloatTensor()

In [79]:
a.type()

'torch.FloatTensor'

In [80]:
a=t.arange(0,6).view(2,3)

In [81]:
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [82]:
a.type()

'torch.LongTensor'